/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var m;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);function q(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}
q("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,k){this.ta=f;p(this,"description",{configurable:!0,writable:!0,value:k})}if(a)return a;c.prototype.toString=function(){return this.ta};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function ea(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var fa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ha;
if("function"==typeof Object.setPrototypeOf)ha=Object.setPrototypeOf;else{var ia;a:{var ja={a:!0},ka={};try{ka.__proto__=ja;ia=ka.a;break a}catch(a){}ia=!1}ha=ia?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var la=ha;function r(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
q("WeakMap",function(a){function b(h){this.L=(g+=Math.random()+1).toString();if(h){h=ea(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(h){var l=typeof h;return"object"===l&&null!==h||"function"===l}function e(h){if(!r(h,k)){var l=new c;p(h,k,{value:l})}}function f(h){var l=Object[h];l&&(Object[h]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return l(n)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),
n=new a([[h,2],[l,3]]);if(2!=n.get(h)||3!=n.get(l))return!1;n.delete(h);n.set(l,4);return!n.has(h)&&4==n.get(l)}catch(F){return!1}}())return a;var k="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var g=0;b.prototype.set=function(h,l){if(!d(h))throw Error("Invalid WeakMap key");e(h);if(!r(h,k))throw Error("WeakMap key fail: "+h);h[k][this.L]=l;return this};b.prototype.get=function(h){return d(h)&&r(h,k)?h[k][this.L]:void 0};b.prototype.has=function(h){return d(h)&&r(h,
k)&&r(h[k],this.L)};b.prototype.delete=function(h){return d(h)&&r(h,k)&&r(h[k],this.L)?delete h[k][this.L]:!1};return b});
q("Map",function(a){function b(){var g={};return g.previous=g.next=g.head=g}function c(g,h){var l=g.v;return da(function(){if(l){for(;l.head!=g.v;)l=l.previous;for(;l.next!=l.head;)return l=l.next,{done:!1,value:h(l)};l=null}return{done:!0,value:void 0}})}function d(g,h){var l=h&&typeof h;"object"==l||"function"==l?f.has(h)?l=f.get(h):(l=""+ ++k,f.set(h,l)):l="p_"+h;var n=g.I[l];if(n&&r(g.I,l))for(g=0;g<n.length;g++){var F=n[g];if(h!==h&&F.key!==F.key||h===F.key)return{id:l,list:n,index:g,entry:F}}return{id:l,
list:n,index:-1,entry:void 0}}function e(g){this.I={};this.v=b();this.size=0;if(g){g=ea(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),h=new a(ea([[g,"s"]]));if("s"!=h.get(g)||1!=h.size||h.get({x:4})||h.set({x:4},"t")!=h||2!=h.size)return!1;var l=h.entries(),n=l.next();if(n.done||n.value[0]!=g||"s"!=n.value[1])return!1;n=l.next();return n.done||4!=
n.value[0].x||"t"!=n.value[1]||!l.next().done?!1:!0}catch(F){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(g,h){g=0===g?0:g;var l=d(this,g);l.list||(l.list=this.I[l.id]=[]);l.entry?l.entry.value=h:(l.entry={next:this.v,previous:this.v.previous,head:this.v,key:g,value:h},l.list.push(l.entry),this.v.previous.next=l.entry,this.v.previous=l.entry,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.I[g.id],
g.entry.previous.next=g.entry.next,g.entry.next.previous=g.entry.previous,g.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.I={};this.v=this.v.previous=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).entry};e.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,
function(g){return g.value})};e.prototype.forEach=function(g,h){for(var l=this.entries(),n;!(n=l.next()).done;)n=n.value,g.call(h,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var k=0;return e});function ma(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}
q("Array.prototype.entries",function(a){return a?a:function(){return ma(this,function(b,c){return[b,c]})}});q("Array.prototype.keys",function(a){return a?a:function(){return ma(this,function(b){return b})}});
q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(g){return g};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var k=0;!(f=b.next()).done;)e.push(c.call(d,f.value,k++))}else for(f=b.length,k=0;k<f;k++)e.push(c.call(d,b[k],k));return e}});q("Array.prototype.values",function(a){return a?a:function(){return ma(this,function(b,c){return c})}});
q("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)r(b,d)&&c.push([d,b[d]]);return c}});q("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)r(b,d)&&c.push(b[d]);return c}});var t=this||self;function u(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"}function v(a){var b=u(a);return"array"==b||"object"==b&&"number"==typeof a.length}function w(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
var na="closure_uid_"+(1E9*Math.random()>>>0),oa=0;function pa(a,b,c){return a.call.apply(a.bind,arguments)}function qa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function ra(a,b,c){ra=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?pa:qa;return ra.apply(null,arguments)}function x(a,b){function c(){}c.prototype=b.prototype;a.T=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ed=function(d,e,f){for(var k=Array(arguments.length-2),g=2;g<arguments.length;g++)k[g-2]=arguments[g];return b.prototype[e].apply(d,k)}}function sa(a){return a};var ta={Ga:"n_amt",Ia:"n_afoiu",Ja:"n_age",Ka:"n_k",La:"n_ars",Ma:"n_s",Na:"n_ss",Oa:"n_ats",Pa:"n_atas",Sa:"n_bi",Ta:"n_bl",Xa:"n_ccd",Ya:"n_cc",Za:"n_c",ab:"n_cp",bb:"n_csbs",gb:"n_dt",jb:"n_deau",kb:"n_detl",mb:"n_eau",nb:"n_ecmv3m",ob:"n_ecil",pb:"n_ecpde",qb:"n_edmp",rb:"n_edtt",sb:"n_edlh",tb:"n_efab",ub:"n_eh",vb:"n_eil",wb:"n_eliw",xb:"n_eml",yb:"n_emv2dm",zb:"n_eod",Ab:"n_eoros",Bb:"n_ep",Cb:"n_erhu",Eb:"n_ei",Fb:"n_fpae",Lb:"n_hak",Nb:"n_imb",Ob:"n_imp",Rb:"n_iup",Qb:"n_iltrup",Tb:"n_j",
Ub:"n_kud",Yb:"n_lcu",ac:"n_mpak",bc:"n_mpau",ic:"n_nmri",fc:"n_nib",hc:"n_nmb",kc:"n_npd",lc:"n_npv",mc:"n_oe",pc:"n_pau",vc:"n_rs",xc:"n_rau",Bc:"n_ses",Dc:"n_scp",Fc:"n_sit",Gc:"n_t",Kc:"n_ton",Hc:"n_tak",Jc:"n_tipe",Ic:"n_tbti",Lc:"n_taau",Mc:"n_tcu",Nc:"n_tcur",Pc:"n_tms",Oc:"n_the",Rc:"n_ur",Sc:"n_uptc",Pb:"n_ugat",Wc:"n_uo",Vc:"n_ui",Tc:"n_ue",Uc:"n_ugs",cd:"n_wfp",dd:"n_wcv"};function y(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,y);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}x(y,Error);y.prototype.name="CustomError";var z;function ua(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");y.call(this,c+a[d])}x(ua,y);ua.prototype.name="AssertionError";function va(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new ua(""+e,f||[]);}function A(a,b,c){a||va("",null,b,Array.prototype.slice.call(arguments,2));return a}function B(a,b){throw new ua("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));}
function C(a,b,c){"number"!==typeof a&&va("Expected number but got %s: %s.",[u(a),a],b,Array.prototype.slice.call(arguments,2));return a}function wa(a,b,c){"string"!==typeof a&&va("Expected string but got %s: %s.",[u(a),a],b,Array.prototype.slice.call(arguments,2))}function xa(a,b,c){Array.isArray(a)||va("Expected array but got %s: %s.",[u(a),a],b,Array.prototype.slice.call(arguments,2))};function ya(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function za(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}function Aa(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};function Ba(){var a={DEFAULT:0,DARK:1};this.S={};this.la={};if(a)for(var b in a)this.put(b,a[b])}Ba.prototype.put=function(a,b){A(void 0===this.S[a]);A(void 0===this.la[b]);this.S[a]=b;this.la[b]=a};Ba.prototype.get=function(a){return this.S[a]};Ba.prototype.P=function(){return Aa(this.S)};var Ca=/&/g,Da=/</g,Ea=/>/g,Fa=/"/g,Ga=/'/g,Ha=/\x00/g,Ia=/[\x00&<>"']/;var Ja,Ka;a:{for(var La=["CLOSURE_FLAGS"],Ma=t,Na=0;Na<La.length;Na++)if(Ma=Ma[La[Na]],null==Ma){Ka=null;break a}Ka=Ma}var Oa=Ka&&Ka[610401301];Ja=null!=Oa?Oa:!1;function Pa(){var a=t.navigator;return a&&(a=a.userAgent)?a:""}var D,Qa=t.navigator;D=Qa?Qa.userAgentData||null:null;function Ra(a){return Ja?D?D.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function E(a){return-1!=Pa().indexOf(a)};function G(){return Ja?!!D&&0<D.brands.length:!1}function Sa(){return G()?Ra("Chromium"):(E("Chrome")||E("CriOS"))&&!(G()?0:E("Edge"))||E("Silk")};var Ta=Array.prototype.indexOf?function(a,b){A(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ua=Array.prototype.forEach?function(a,b){A(null!=a.length);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function Va(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Wa(a){Wa[" "](a);return a}Wa[" "]=function(){};var Xa=G()?!1:E("Trident")||E("MSIE"),Ya=E("Gecko")&&!(-1!=Pa().toLowerCase().indexOf("webkit")&&!E("Edge"))&&!(E("Trident")||E("MSIE"))&&!E("Edge"),Za=-1!=Pa().toLowerCase().indexOf("webkit")&&!E("Edge");!E("Android")||Sa();Sa();var $a=E("Safari")&&!(Sa()||(G()?0:E("Coast"))||(G()?0:E("Opera"))||(G()?0:E("Edge"))||(G()?Ra("Microsoft Edge"):E("Edg/"))||(G()?Ra("Opera"):E("OPR"))||E("Firefox")||E("FxiOS")||E("Silk")||E("Android"))&&!(E("iPhone")&&!E("iPod")&&!E("iPad")||E("iPad")||E("iPod"));var H=null,ab=Ya||Za||!$a&&!Xa&&"function"==typeof t.atob;function bb(a,b){function c(h){for(;d<a.length;){var l=a.charAt(d++),n=H[l];if(null!=n)return n;if(!/^[\s\xa0]*$/.test(l))throw Error("Unknown base64 encoding at char: "+l);}return h}cb();for(var d=0;;){var e=c(-1),f=c(0),k=c(64),g=c(64);if(64===g&&-1===e)break;b(e<<2|f>>4);64!=k&&(b(f<<4&240|k>>2),64!=g&&b(k<<6&192|g))}}
function cb(){if(!H){H={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++)for(var d=a.concat(b[c].split("")),e=0;e<d.length;e++){var f=d[e],k=H[f];void 0===k?H[f]=e:A(k===e)}}};A(!0);var db="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol("INTERNAL_ARRAY_STATE"):void 0,eb=Object.getOwnPropertyDescriptor(Array.prototype,"Ca");
Object.defineProperties(Array.prototype,{Ca:{get:function(){function a(e,f){e&b&&c.push(f)}var b=fb(this),c=[];a(1,"IS_REPEATED_FIELD");a(2,"IS_IMMUTABLE_ARRAY");a(4,"IS_API_FORMATTED");a(8,"ONLY_MUTABLE_VALUES");a(16,"MUTABLE_REFERENCES_ARE_OWNED");a(32,"CONSTRUCTED");a(64,"TRANSFERRED");var d=c.join(",");return eb?eb.get.call(this)+"|"+d:d},configurable:!0,enumerable:!1}});function fb(a){xa(a,"state is only maintained on arrays.");a=db?a[db]:a.fd;return null==a?0:a};function gb(){throw Error("please construct maps as mutable then call toImmutable");}
if("undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance){var hb=function(){throw Error("Cannot perform instanceof checks on ImmutableMap: please use isImmutableMap or isMutableMap to assert on the mutability of a map. See go/jspb-api-gotchas#immutable-classes for more information");},ib={};Object.defineProperties(gb,(ib[Symbol.hasInstance]={value:hb,configurable:!1,writable:!1,enumerable:!1},ib));A(gb[Symbol.hasInstance]===hb,"defineProperties did not work: was it monkey-patched?")};if("undefined"!==typeof Proxy){var I=jb;new Proxy({},{getPrototypeOf:I,setPrototypeOf:I,isExtensible:I,preventExtensions:I,getOwnPropertyDescriptor:I,defineProperty:I,has:I,get:I,set:I,deleteProperty:I,apply:I,construct:I})}function jb(){throw Error("this array or object is owned by JSPB and should not be reused, did you mean to copy it with copyJspbArray? See go/jspb-api-gotchas#construct_from_array");throw Error();};function kb(){};(function(){var a=t.jspbGetTypeName;t.jspbGetTypeName=a?function(b){return a(b)||void 0}:kb})();var lb={Ha:"activedescendant",Qa:"atomic",Ra:"autocomplete",Ua:"busy",Wa:"checked",cb:"colindex",eb:"controls",fb:"current",ib:"describedby",DISABLED:"disabled",lb:"dropeffect",Db:"expanded",Gb:"flowto",Ib:"grabbed",Kb:"haspopup",Mb:"hidden",Sb:"invalid",Vb:"label",Wb:"labelledby",Xb:"level",Zb:"live",cc:"multiline",dc:"multiselectable",nc:"orientation",oc:"owns",rc:"posinset",sc:"pressed",tc:"readonly",wc:"relevant",yc:"required",zc:"rowindex",Ac:"selected",Cc:"setsize",Ec:"sort",Xc:"valuemax",Yc:"valuemin",
Zc:"valuenow",ad:"valuetext"};var mb;try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var nb;function J(a,b){this.ea=a===ob&&b||"";this.ua=pb}J.prototype.G=!0;J.prototype.C=function(){return this.ea};J.prototype.toString=function(){return"Const{"+this.ea+"}"};function qb(a){if(a instanceof J&&a.constructor===J&&a.ua===pb)return a.ea;B("expected object of type Const, got '"+a+"'");return"type_error:Const"}var pb={},ob={};function K(a,b){if(b!==L)throw Error("SafeUrl is not meant to be built directly");this.ca=a}K.prototype.toString=function(){return this.ca.toString()};K.prototype.G=!0;K.prototype.C=function(){return this.ca.toString()};var L={};new K("about:invalid#zClosurez",L);new K("about:blank",L);var rb={};function sb(){if(rb!==rb)throw Error("SafeStyle is not meant to be built directly");this.ra="";this.G=!0}sb.prototype.C=function(){return this.ra};sb.prototype.toString=function(){return this.ra.toString()};new sb;var tb={};function ub(){if(tb!==tb)throw Error("SafeStyleSheet is not meant to be built directly");this.qa="";this.G=!0}ub.prototype.toString=function(){return this.qa.toString()};ub.prototype.C=function(){return this.qa};new ub;var vb={};function M(a,b){if(b!==vb)throw Error("SafeHtml is not meant to be built directly");this.ba=a;this.G=!0}M.prototype.C=function(){return this.ba.toString()};M.prototype.toString=function(){return this.ba.toString()};function wb(a){if(a instanceof M&&a.constructor===M)return a.ba;B("expected object of type SafeHtml, got '"+a+"' of type "+u(a));return"type_error:SafeHtml"}
function xb(a){a instanceof M||(a="object"==typeof a&&a.G?a.C():String(a),Ia.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(Ca,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(Da,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(Ea,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(Fa,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(Ga,"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(Ha,"&#0;"))),a=yb(a));return a}
function yb(a){if(void 0===nb){var b=null;var c=t.trustedTypes;if(c&&c.createPolicy)try{b=c.createPolicy("goog#html",{createHTML:sa,createScript:sa,createScriptURL:sa})}catch(d){t.console&&t.console.error(d.message)}nb=b}a=(b=nb)?b.createHTML(a):a;return new M(a,vb)}var zb=new M(t.trustedTypes&&t.trustedTypes.emptyHTML||"",vb);var Ab=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if("undefined"===typeof document)return!1;var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);if(!a.firstChild)return!1;b=a.firstChild.firstChild;a.innerHTML=wb(zb);return!b.parentElement});var Bb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Cb(a,b,c){function d(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):g)}for(var e=1;e<c.length;e++){var f=c[e];if(!v(f)||w(f)&&0<f.nodeType)d(f);else{a:{if(f&&"number"==typeof f.length){if(w(f)){var k="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){k="function"==typeof f.item;break a}}k=!1}Ua(k?Va(f):f,d)}}}function Db(a){A(a,"Node cannot be null or undefined.");return 9==a.nodeType?a:a.ownerDocument||a.document}
function Eb(){this.J=t.document||document}m=Eb.prototype;m.getElementsByTagName=function(a,b){return(b||this.J).getElementsByTagName(String(a))};m.setProperties=function(a,b){ya(b,function(c,d){c&&"object"==typeof c&&c.G&&(c=c.C());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Bb.hasOwnProperty(d)?a.setAttribute(Bb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})};
m.createElement=function(a){var b=this.J;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};m.createTextNode=function(a){return this.J.createTextNode(String(a))};m.getWindow=function(){var a=this.J;return a.parentWindow||a.defaultView};m.appendChild=function(a,b){A(null!=a&&null!=b,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};m.append=function(a,b){Cb(Db(a),a,arguments)};
m.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};m.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};
m.getChildren=function(a){return void 0!=a.children?a.children:Array.prototype.filter.call(a.childNodes,function(b){return 1==b.nodeType})};m.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function Fb(a,b,c){Array.isArray(c)&&(c=c.join(" "));var d=Gb(b);""===c||void 0==c?(mb||(c={},mb=(c.atomic=!1,c.autocomplete="none",c.dropeffect="none",c.haspopup=!1,c.live="off",c.multiline=!1,c.multiselectable=!1,c.orientation="vertical",c.readonly=!1,c.relevant="additions text",c.required=!1,c.sort="none",c.busy=!1,c.disabled=!1,c.hidden=!1,c.invalid="false",c)),c=mb,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function Gb(a){A(a,"ARIA attribute cannot be empty.");a:{for(b in lb)if(lb[b]==a){var b=!0;break a}b=!1}A(b,"No such ARIA attribute "+a);return"aria-"+a};function Hb(){this.W=this.W}Hb.prototype.W=!1;Hb.prototype.isDisposed=function(){return this.W};function Ib(a){Hb.call(this);this.ha=a||z||(z=new Eb);this.oa={};this.na={}}x(Ib,Hb);var Jb=[];function Kb(a){A(!Object.isSealed(a),"Cannot use getInstance() with a sealed constructor.");var b="Z";if(a.Z&&a.hasOwnProperty(b))return a.Z;Jb.push(a);var c=new a;a.Z=c;A(a.hasOwnProperty(b),"Could not instantiate singleton.");return c};function Lb(){this.va=new Ib}
Lb.prototype.speak=function(a,b){var c=this.va;b=b||"polite";var d;if(d=c.oa[b])d.removeAttribute(Gb("hidden"));else{var e=d=c.ha.createElement("DIV");var f=d;f=Object.prototype.hasOwnProperty.call(f,na)&&f[na]||(f[na]=++oa);e.id="goog-lr-"+f;d.style.position="absolute";d.style.top="-1000px";d.style.height="1px";d.style.overflow="hidden";Fb(d,"live",b);Fb(d,"atomic","true");c.ha.J.body.appendChild(d);c.oa[b]=d}e=(e=c.na[b])&&e===a?a+"\u00a0":a;a&&(c.na[b]=e);A(null!=d,"goog.dom.setTextContent expects a non-null value for node");
if("textContent"in d)d.textContent=e;else if(3==d.nodeType)d.data=String(e);else if(d.firstChild&&3==d.firstChild.nodeType){for(;d.lastChild!=d.firstChild;)d.removeChild(A(d.lastChild));d.firstChild.data=String(e)}else{for(;a=d.firstChild;)d.removeChild(a);a=Db(d);d.appendChild(a.createTextNode(String(e)))}};function Mb(a){if(a.D&&"function"==typeof a.D)return a.D();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(v(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function Nb(a){if(a.P&&"function"==typeof a.P)return a.P();if(!a.D||"function"!=typeof a.D){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&a instanceof Set)){if(v(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}return Aa(a)}}}
function Ob(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(v(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,c);else for(var d=Nb(a),e=Mb(a),f=e.length,k=0;k<f;k++)b.call(c,e[k],d&&d[k],a)};var Pb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Qb(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function N(a){this.u=this.F=this.A="";this.H=null;this.B=this.s="";this.m=this.Ba=!1;if(a instanceof N){this.m=a.m;Rb(this,a.A);var b=a.F;O(this);this.F=b;b=a.u;O(this);this.u=b;Sb(this,a.H);b=a.s;O(this);this.s=b;Tb(this,a.o.clone());a=a.B;O(this);this.B=a}else a&&(b=String(a).match(Pb))?(this.m=!1,Rb(this,b[1]||"",!0),a=b[2]||"",O(this),this.F=P(a),a=b[3]||"",O(this),this.u=P(a,!0),Sb(this,b[4]),a=b[5]||"",O(this),this.s=P(a,!0),Tb(this,b[6]||"",!0),a=b[7]||"",O(this),this.B=P(a)):(this.m=!1,this.o=
new Q(null,this.m))}m=N.prototype;m.toString=function(){var a=[],b=this.A;b&&a.push(R(b,Ub,!0),":");var c=this.u;if(c||"file"==b)a.push("//"),(b=this.F)&&a.push(R(b,Ub,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.H,null!=c&&a.push(":",String(c));if(c=this.s)this.u&&"/"!=c.charAt(0)&&a.push("/"),a.push(R(c,"/"==c.charAt(0)?Vb:Wb,!0));(c=this.o.toString())&&a.push("?",c);(c=this.B)&&a.push("#",R(c,Xb));return a.join("")};
m.resolve=function(a){var b=this.clone(),c=!!a.A;c?Rb(b,a.A):c=!!a.F;if(c){var d=a.F;O(b);b.F=d}else c=!!a.u;c?(d=a.u,O(b),b.u=d):c=null!=a.H;d=a.s;if(c)Sb(b,a.H);else if(c=!!a.s){if("/"!=d.charAt(0))if(this.u&&!this.s)d="/"+d;else{var e=b.s.lastIndexOf("/");-1!=e&&(d=b.s.slice(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],k=0;k<e.length;){var g=e[k++];"."==g?d&&k==e.length&&f.push(""):".."==g?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),d&&k==e.length&&f.push("")):(f.push(g),d=!0)}d=f.join("/")}else d=e}c?(O(b),b.s=d):c=""!==a.o.toString();c?Tb(b,a.o.clone()):c=!!a.B;c&&(a=a.B,O(b),b.B=a);return b};m.clone=function(){return new N(this)};function Rb(a,b,c){O(a);a.A=c?P(b,!0):b;a.A&&(a.A=a.A.replace(/:$/,""))}function Sb(a,b){O(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.H=b}else a.H=null}
function Tb(a,b,c){O(a);b instanceof Q?(a.o=b,a.o.da(a.m)):(c||(b=R(b,Yb)),a.o=new Q(b,a.m))}m.getQuery=function(){return this.o.toString()};m.removeParameter=function(a){O(this);this.o.remove(a);return this};function O(a){if(a.Ba)throw Error("Tried to modify a read-only Uri");}m.da=function(a){this.m=a;this.o&&this.o.da(a)};function P(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}
function R(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Zb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Zb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Ub=/[#\/\?@]/g,Wb=/[#\?:]/g,Vb=/[#\?]/g,Yb=/[#\?@]/g,Xb=/#/g;function Q(a,b){this.i=this.g=null;this.l=a||null;this.m=!!b}function S(a){a.g||(a.g=new Map,a.i=0,a.l&&Qb(a.l,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}m=Q.prototype;
m.add=function(a,b){S(this);this.l=null;a=T(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.i=C(this.i)+1;return this};m.remove=function(a){S(this);a=T(this,a);return this.g.has(a)?(this.l=null,this.i=C(this.i)-this.g.get(a).length,this.g.delete(a)):!1};m.clear=function(){this.g=this.l=null;this.i=0};function $b(a,b){S(a);b=T(a,b);return a.g.has(b)}m.forEach=function(a,b){S(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};
m.P=function(){S(this);for(var a=Array.from(this.g.values()),b=Array.from(this.g.keys()),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};m.D=function(a){S(this);var b=[];if("string"===typeof a)$b(this,a)&&(b=b.concat(this.g.get(T(this,a))));else{a=Array.from(this.g.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};
m.set=function(a,b){S(this);this.l=null;a=T(this,a);$b(this,a)&&(this.i=C(this.i)-this.g.get(a).length);this.g.set(a,[b]);this.i=C(this.i)+1;return this};m.get=function(a,b){if(!a)return b;a=this.D(a);return 0<a.length?String(a[0]):b};
m.toString=function(){if(this.l)return this.l;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.D(d);for(var f=0;f<d.length;f++){var k=e;""!==d[f]&&(k+="="+encodeURIComponent(String(d[f])));a.push(k)}}return this.l=a.join("&")};m.clone=function(){var a=new Q;a.l=this.l;this.g&&(a.g=new Map(this.g),a.i=this.i);return a};function T(a,b){b=String(b);a.m&&(b=b.toLowerCase());return b}
m.da=function(a){a&&!this.m&&(S(this),this.l=null,this.g.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<b.length&&(this.l=null,this.g.set(T(this,d),Va(b)),this.i=C(this.i)+b.length))},this));this.m=a};m.extend=function(a){for(var b=0;b<arguments.length;b++)Ob(arguments[b],function(c,d){this.add(d,c)},this)};function ac(){this.ja={};bc(this,t._notes_flag_initialData||{});cc(this)}function bc(a,b){ya(ta,function(c){void 0!==b[c]&&(a.ja[c]=b[c])})}function cc(a){var b={};(new N(self.location.href)).o.forEach(function(c,d){b[d]=c});bc(a,b)};Object.values({UNKNOWN:"unknown",hb:"default",Jb:"groceries",Hb:"food",ec:"music",uc:"recipes",jc:"notes",qc:"places",Qc:"travel",bd:"video",Va:"celebration"}).filter(function(a){return"unknown"!==a});var dc=Object.freeze||function(a){return a};function ec(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=!1}ec.prototype.stopPropagation=function(){};ec.prototype.preventDefault=function(){this.defaultPrevented=!0};var fc=function(){if(!t.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};t.addEventListener("test",c,b);t.removeEventListener("test",c,b)}catch(d){}return a}();function U(a,b){ec.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.K=null;a&&this.init(a,b)}x(U,ec);var gc=dc({2:"touch",3:"pen",4:"mouse"});
U.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(Ya){a:{try{Wa(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=
d.screenY||0):(this.offsetX=Za||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=Za||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=
a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:gc[a.pointerType]||"";this.state=a.state;this.K=a;a.defaultPrevented&&U.T.preventDefault.call(this)};U.prototype.stopPropagation=function(){U.T.stopPropagation.call(this);this.K.stopPropagation?this.K.stopPropagation():this.K.cancelBubble=!0};U.prototype.preventDefault=function(){U.T.preventDefault.call(this);var a=this.K;a.preventDefault?a.preventDefault():a.returnValue=!1};var hc="closure_listenable_"+(1E6*Math.random()|0);var ic=0;function jc(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.X=e;this.key=++ic;this.removed=this.V=!1}function kc(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.X=null};function lc(a){this.src=a;this.j={};this.M=0}m=lc.prototype;m.add=function(a,b,c,d,e){var f=a.toString();a=this.j[f];a||(a=this.j[f]=[],this.M++);var k=mc(a,b,d,e);-1<k?(b=a[k],c||(b.V=!1)):(b=new jc(b,this.src,f,!!d,e),b.V=c,a.push(b));return b};m.remove=function(a,b,c,d){a=a.toString();if(!(a in this.j))return!1;var e=this.j[a];b=mc(e,b,c,d);return-1<b?(kc(e[b]),A(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.j[a],this.M--),!0):!1};
function nc(a,b){var c=b.type;if(c in a.j){var d=a.j[c],e=Ta(d,b),f;if(f=0<=e)A(null!=d.length),Array.prototype.splice.call(d,e,1);f&&(kc(b),0==a.j[c].length&&(delete a.j[c],a.M--))}}m.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.j)if(!a||c==a){for(var d=this.j[c],e=0;e<d.length;e++)++b,kc(d[e]);delete this.j[c];this.M--}return b};m.ya=function(a,b,c,d){a=this.j[a.toString()];var e=-1;a&&(e=mc(a,b,c,d));return-1<e?a[e]:null};
m.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return za(this.j,function(f){for(var k=0;k<f.length;++k)if(!(c&&f[k].type!=d||e&&f[k].capture!=b))return!0;return!1})};function mc(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.X==d)return e}return-1};var oc="closure_lm_"+(1E6*Math.random()|0),pc={},qc=0;function rc(a,b,c,d,e){if(d&&d.once)sc(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)rc(a,b[f],c,d,e);else c=tc(c),a&&a[hc]?a.listen(b,c,w(d)?!!d.capture:!!d,e):uc(a,b,c,!1,d,e)}
function uc(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=w(e)?!!e.capture:!!e,g=vc(a);g||(a[oc]=g=new lc(a));c=g.add(b,c,d,k,f);if(!c.proxy){d=wc();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)fc||(e=k),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(xc(b.toString()),d);else if(a.addListener&&a.removeListener)A("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");
qc++}}function wc(){function a(c){return b.call(a.src,a.listener,c)}var b=yc;return a}function sc(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)sc(a,b[f],c,d,e);else c=tc(c),a&&a[hc]?a.ia.add(String(b),c,!0,w(d)?!!d.capture:!!d,e):uc(a,b,c,!0,d,e)}function zc(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)zc(a,b[f],c,d,e);else d=w(d)?!!d.capture:!!d,c=tc(c),a&&a[hc]?a.ia.remove(String(b),c,d,e):a&&(a=vc(a))&&(b=a.ya(b,c,d,e))&&Ac(b)}
function Ac(a){if("number"!==typeof a&&a&&!a.removed){var b=a.src;if(b&&b[hc])nc(b.ia,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(xc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);qc--;(c=vc(b))?(nc(c,a),0==c.M&&(c.src=null,b[oc]=null)):kc(a)}}}function xc(a){return a in pc?pc[a]:pc[a]="on"+a}function yc(a,b){if(a.removed)a=!0;else{b=new U(b,this);var c=a.listener,d=a.X||a.src;a.V&&Ac(a);a=c.call(d,b)}return a}
function vc(a){a=a[oc];return a instanceof lc?a:null}var Bc="__closure_events_fn_"+(1E9*Math.random()>>>0);function tc(a){A(a,"Listener can not be null.");if("function"===typeof a)return a;A(a.handleEvent,"An object listener must have handleEvent method.");a[Bc]||(a[Bc]=function(b){return a.handleEvent(b)});return a[Bc]};function V(){this.U=[];new DataView(new ArrayBuffer(8))}function W(){}V.prototype=fa(W.prototype);V.prototype.constructor=V;if(la)la(V,W);else for(var X in W)if("prototype"!=X)if(Object.defineProperties){var Cc=Object.getOwnPropertyDescriptor(W,X);Cc&&Object.defineProperty(V,X,Cc)}else V[X]=W[X];V.T=W.prototype;new V;new Ba;(function(a,b){if(ab&&!b)return t.atob(a);var c="";bb(a,function(d){c+=String.fromCharCode(d)});return c})("bGFiZWxz");Object.freeze("annotationsGroup isArchived isDirty isPinned lastSyncedText parentServerId reminder baseVersion baseNoteRevision serverId shareState roleInfo showAvailableInShoppingNotification timestamps".split(" "));new K(qb(new J(ob,"http://goo.gl/forms/r40gTO4BTb")),L);new K(qb(new J(ob,"https://keep.google.com")),L);function Dc(a,b){this.name=a;this.value=b}Dc.prototype.toString=function(){return this.name};var Ec=new Dc("OFF",Infinity),Fc=new Dc("WARNING",900),Gc=new Dc("CONFIG",700);function Hc(){this.O=0;this.clear()}var Ic;Hc.prototype.clear=function(){this.U=Array(this.O);this.ga=-1;this.ma=!1};function Jc(a,b,c){this.reset(a||Ec,b,c,void 0,void 0)}Jc.prototype.reset=function(a,b){this.Ea=b};Jc.prototype.getMessage=function(){return this.Ea};
function Kc(a,b){this.level=null;this.Aa=[];this.parent=(void 0===b?null:b)||null;this.children=[];this.Da={getName:function(){return a}}}function Lc(a){if(a.level)return a.level;if(a.parent)return Lc(a.parent);B("Root logger has no level set.");return Ec}Kc.prototype.publish=function(a){for(var b=this;b;)b.Aa.forEach(function(c){c(a)}),b=b.parent};function Mc(){this.entries={};var a=new Kc("");a.level=Gc;this.entries[""]=a}var Nc;
function Oc(a,b){var c=a.entries[b];if(c)return c;c=Oc(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var d=new Kc(b,c);a.entries[b]=d;c.children.push(d);return d}function Pc(){Nc||(Nc=new Mc);return Nc};/*

 SPDX-License-Identifier: Apache-2.0
*/
var Qc;try{new URL("s://g"),Qc=!0}catch(a){Qc=!1}var Rc=Qc,Sc=[];function Tc(){}
Uc(function(a){var b;if(b=Oc(Pc(),"safevalues").Da){var c="A URL with content '"+a+"' was sanitized away.",d=Fc;if(a=b)if(a=b&&d){a=d.value;var e=b?Lc(Oc(Pc(),b.getName())):Ec;a=a>=e.value}if(a){d=d||Ec;a=Oc(Pc(),b.getName());"function"===typeof c&&(c=c());Ic||(Ic=new Hc);e=Ic;b=b.getName();if(0<e.O){var f=(e.ga+1)%e.O;e.ga=f;e.ma?(e=e.U[f],e.reset(d,c,b),b=e):(e.ma=f==e.O-1,b=e.U[f]=new Jc(d,c,b))}else b=new Jc(d,c,b);a.publish(b)}}});
function Uc(a){-1===Sc.indexOf(a)&&Sc.push(a);Tc=function(b){Sc.forEach(function(c){c(b)})}};var Vc={gd:!0};function Y(){throw Error("Do not instantiate directly");}Y.prototype.wa=null;Y.prototype.getContent=function(){return this.content};Y.prototype.toString=function(){return this.content};
Y.prototype.sa=function(){if(this.xa!==Vc)throw Error("Sanitized content was not of kind HTML.");var a=this.toString(),b=new J(ob,"Soy SanitizedContent of kind HTML produces SafeHtml-contract-compliant value.");wa(qb(b),"must provide justification");A(!/^[\s\xa0]*$/.test(qb(b)),"must provide non-empty justification");return yb(a)};function Wc(){Y.call(this)}x(Wc,Y);Wc.prototype.xa=Vc;var Xc=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.wa=d);return c}}(Wc),Yc={};/*
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Zc=/^<(body|caption|col|colgroup|head|html|tr|td|th|tbody|thead|tfoot)>/i,$c={};function ad(){var a=Kb(ac).ja.n_ecmv3m;this.R=!!a&&"false"!==a;this.h=null;this.aa=!1;this.fa="";this.R&&(this.N={});this.R||(this.Y(),rc(document,"mousedown",this.ka,void 0,this),a={},a.imageUrl=bd(),Z(this,"pageScrape",a));this.pa=ra(this.za,this);chrome.runtime.onMessage.addListener(this.pa)}function cd(a){a.h=null;a.R||zc(document,"mousedown",a.ka,void 0,a);chrome.runtime.onMessage.removeListener(a.pa);a.aa=!0}
function Z(a,b,c){if(!a.aa)try{chrome.runtime.sendMessage(chrome.runtime.id,{type:b,value:c},void 0)}catch(d){cd(a)}}
function bd(){for(var a="",b=document.getElementsByTagName("META"),c=0,d;d=b[c];c++)if("og:image"==d.getAttribute("property")){a=d.getAttribute("content");break}if(!a){b=0;c=document.getElementsByTagName("IMG");d=0;for(var e;e=c[d];d++){var f=e.naturalWidth||e.width,k=e.naturalHeight||e.height;if(128<=k&&128<=f&&k*f>b){b=k*f;var g=e.src}}g&&(a=g)}a&&(a=a instanceof N?a.clone():new N(a),a.A||Rb(a,"http"),a=a.toString());return a}
ad.prototype.za=function(a,b,c){if(w(a)&&!this.aa)switch(a.type){case "appHeightChange":this.h&&(this.h.style.height=a.value);break;case "dispose":cd(this);break;case "finishHide":this.h&&dd(this,!1);break;case "getInitInfo":c(this.N);break;case "getSelectedText":c(window.getSelection().toString());break;case "removeIframe":this.h.parentNode.removeChild(this.h),cd(this);case "selectedTextRequest":c(window.getSelection().toString());break;case "setInitInfo":this.N=a.value;this.N.selectedText=window.getSelection().toString();
this.N.embedInfo.imageUrl=bd();this.Y();break;case "speakMessage":Kb(Lb).speak(a.value);break;case "show":this.h&&dd(this,!0);break;case "toggleVisibility":a="none"==this.h.style.display,this.h&&("none"==this.h.style.display?(dd(this,!0),this.h.contentWindow.focus(),Z(this,"show")):(Z(this,"startHide"),Z(this,"impression",9204))),c(a)}};
ad.prototype.Y=function(){if("interactive"!=document.readyState&&"complete"!=document.readyState)rc(document,"DOMContentLoaded",this.Y,void 0,this);else{if(this.R){var a=document.getElementById("keep-popup-frame");a&&a.parentNode&&a.parentNode.removeChild(a)}var b=Yc["notes.browseraction.soy.injects.injectedIframe"]?Yc["notes.browseraction.soy.injects.injectedIframe"]($c,void 0):Xc('<iframe frameborder="0" style=" height: 438px; margin: 0px; padding: 0px; position: fixed; right: 5px; top: 5px; width: 370px; z-index: 2147483647;"></iframe>');
a=z||(z=new Eb);if(b&&b.Fa)a=b.Fa();else{a=a.createElement("DIV");b:if(w(b)){if(b.sa){var c=b.sa();if(c instanceof M){b=c;break b}}B("Soy template output is unsafe for use as HTML: "+b);b=xb("zSoyz")}else b=xb(String(b));c=b.C();var d=c.match(Zc);A(!d,"This template starts with a %s, which cannot be a child of a <div>, as required by soy internals. Consider using goog.soy.renderElement instead.\nTemplate output: %s",d&&d[0],c);c=a;if(Ab())for(;c.lastChild;)c.removeChild(c.lastChild);c.innerHTML=wb(b)}1==
a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));if(!w(a)||!w(a)||!w(a)||1!==a.nodeType||a.namespaceURI&&"http://www.w3.org/1999/xhtml"!==a.namespaceURI||a.tagName.toUpperCase()!=="IFRAME".toString()){b="IFRAME".toString()+"; got: ";if(w(a))try{var e=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(k){e="<object could not be stringified>"}else e=void 0===a?"undefined":null===a?"null":typeof a;B("Argument is not an HTML Element with tag name "+(b+e))}this.h=
a;this.fa=this.h.style.cssText;this.h.id="keep-popup-frame";e=this.h;a=chrome.runtime.getURL("index.html");e.removeAttribute("srcdoc");b="allow-same-origin allow-scripts allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation".split(" ");e.setAttribute("sandbox","");for(c=0;c<b.length;c++)e.sandbox.supports&&!e.sandbox.supports(b[c])||e.sandbox.add(b[c]);if(a instanceof K)if(a instanceof K&&a.constructor===K)var f=a.ca;else B("expected object of type SafeUrl, got '"+
a+"' of type "+u(a)),f="type_error:SafeUrl";else{b:if(Rc){try{f=new URL(a)}catch(k){f="https:";break b}f=f.protocol}else c:{f=document.createElement("a");try{f.href=a}catch(k){f=void 0;break c}f=f.protocol;f=":"===f||""===f?"https:":f}"javascript:"===f?(Tc(a),f=void 0):f=a}void 0!==f&&(e.src=f);this.h.allow="clipboard-write";document.body.appendChild(this.h);dd(this,!0);this.h.contentWindow.focus()}};function dd(a,b){a.h.style.cssText=a.fa+" display: "+(b?"block !important;":"none")}
ad.prototype.ka=function(a){0==a.button&&this.h&&"none"!=this.h.style.display&&(Z(this,"startHide"),Z(this,"impression",9203))};new ad;
