#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
#
# Autostart
#
# Set display from arandr saved script
#sh ~/.screenlayout/monitor.sh 
sxhkd &

#Config bspwm screen 
bspc monitor eDP-1-0 -d 1 2 3 4 5 6 7 &
startup



# Bar
#/usr/bin/polybar -c ~/.config/polybar/config.ini &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
#feh --bg-fill ~/Imágenes/Fondos/fondo.jpg &
#xwallpaper ~/Imágenes/Fondos/fondo.jpg &
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

## Super Key
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &


# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

#Choose US layout default
~/.config/bspwm/scripts/toggle_kb


bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#00ba7a"
bspc config normal_border_color         "#073642"
#bspc config active_border_color         "#56ff00"

#sh $HOME/.config/polybar/launch.sh
