/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var m;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);function q(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}
q("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,k){this.ta=f;p(this,"description",{configurable:!0,writable:!0,value:k})}if(a)return a;c.prototype.toString=function(){return this.ta};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function r(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;function t(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
q("WeakMap",function(a){function b(h){this.L=(g+=Math.random()+1).toString();if(h){h=r(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(h){var l=typeof h;return"object"===l&&null!==h||"function"===l}function e(h){if(!t(h,k)){var l=new c;p(h,k,{value:l})}}function f(h){var l=Object[h];l&&(Object[h]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return l(n)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),
n=new a([[h,2],[l,3]]);if(2!=n.get(h)||3!=n.get(l))return!1;n.delete(h);n.set(l,4);return!n.has(h)&&4==n.get(l)}catch(F){return!1}}())return a;var k="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var g=0;b.prototype.set=function(h,l){if(!d(h))throw Error("Invalid WeakMap key");e(h);if(!t(h,k))throw Error("WeakMap key fail: "+h);h[k][this.L]=l;return this};b.prototype.get=function(h){return d(h)&&t(h,k)?h[k][this.L]:void 0};b.prototype.has=function(h){return d(h)&&t(h,
k)&&t(h[k],this.L)};b.prototype.delete=function(h){return d(h)&&t(h,k)&&t(h[k],this.L)?delete h[k][this.L]:!1};return b});
q("Map",function(a){function b(){var g={};return g.previous=g.next=g.head=g}function c(g,h){var l=g.v;return da(function(){if(l){for(;l.head!=g.v;)l=l.previous;for(;l.next!=l.head;)return l=l.next,{done:!1,value:h(l)};l=null}return{done:!0,value:void 0}})}function d(g,h){var l=h&&typeof h;"object"==l||"function"==l?f.has(h)?l=f.get(h):(l=""+ ++k,f.set(h,l)):l="p_"+h;var n=g.I[l];if(n&&t(g.I,l))for(g=0;g<n.length;g++){var F=n[g];if(h!==h&&F.key!==F.key||h===F.key)return{id:l,list:n,index:g,entry:F}}return{id:l,
list:n,index:-1,entry:void 0}}function e(g){this.I={};this.v=b();this.size=0;if(g){g=r(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),h=new a(r([[g,"s"]]));if("s"!=h.get(g)||1!=h.size||h.get({x:4})||h.set({x:4},"t")!=h||2!=h.size)return!1;var l=h.entries(),n=l.next();if(n.done||n.value[0]!=g||"s"!=n.value[1])return!1;n=l.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!l.next().done?!1:!0}catch(F){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(g,h){g=0===g?0:g;var l=d(this,g);l.list||(l.list=this.I[l.id]=[]);l.entry?l.entry.value=h:(l.entry={next:this.v,previous:this.v.previous,head:this.v,key:g,value:h},l.list.push(l.entry),this.v.previous.next=l.entry,this.v.previous=l.entry,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.I[g.id],
g.entry.previous.next=g.entry.next,g.entry.next.previous=g.entry.previous,g.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.I={};this.v=this.v.previous=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).entry};e.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,
function(g){return g.value})};e.prototype.forEach=function(g,h){for(var l=this.entries(),n;!(n=l.next()).done;)n=n.value,g.call(h,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var k=0;return e});q("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});q("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)t(b,d)&&c.push(b[d]);return c}});
function la(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}q("Array.prototype.entries",function(a){return a?a:function(){return la(this,function(b,c){return[b,c]})}});q("Array.prototype.keys",function(a){return a?a:function(){return la(this,function(b){return b})}});
q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(g){return g};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var k=0;!(f=b.next()).done;)e.push(c.call(d,f.value,k++))}else for(f=b.length,k=0;k<f;k++)e.push(c.call(d,b[k],k));return e}});q("Array.prototype.values",function(a){return a?a:function(){return la(this,function(b,c){return c})}});
q("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)t(b,d)&&c.push([d,b[d]]);return c}});var u=this||self;function v(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"}function w(a){var b=v(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var ma="closure_uid_"+(1E9*Math.random()>>>0),na=0;function oa(a,b,c){return a.call.apply(a.bind,arguments)}
function pa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function qa(a,b,c){qa=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?oa:pa;return qa.apply(null,arguments)}
function y(a,b){function c(){}c.prototype=b.prototype;a.T=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.sd=function(d,e,f){for(var k=Array(arguments.length-2),g=2;g<arguments.length;g++)k[g-2]=arguments[g];return b.prototype[e].apply(d,k)}}function ra(a){return a};var sa={Ga:"n_amt",Ia:"n_afoiu",Ja:"n_age",Ka:"n_k",La:"n_ars",Ma:"n_s",Na:"n_ss",Oa:"n_ats",Pa:"n_atas",Sa:"n_bi",Ta:"n_bl",Va:"n_cajct",Wa:"n_cajstm",Za:"n_ccd",ab:"n_cc",bb:"n_c",cb:"n_cp",eb:"n_csbs",jb:"n_dt",mb:"n_dlis",nb:"n_deau",ob:"n_detl",qb:"n_eau",rb:"n_ecmv3m",sb:"n_ecil",tb:"n_ecpde",ub:"n_edmp",vb:"n_edtt",wb:"n_edlh",xb:"n_efab",yb:"n_eh",zb:"n_eil",Ab:"n_eliw",Bb:"n_eml",Cb:"n_emv2dm",Db:"n_eod",Eb:"n_eoros",Fb:"n_ep",Gb:"n_erhu",Ib:"n_ei",Jb:"n_fpae",Rb:"n_hak",Tb:"n_imb",Ub:"n_imp",
Yb:"n_iup",Xb:"n_iltrup",dc:"n_j",ec:"n_kud",jc:"n_lcu",lc:"n_mpak",mc:"n_mpau",tc:"n_nmri",rc:"n_nib",sc:"n_nmb",vc:"n_npd",wc:"n_npv",xc:"n_oe",Bc:"n_pau",Hc:"n_rs",Jc:"n_rau",Nc:"n_ses",Pc:"n_scp",Rc:"n_sit",Sc:"n_t",Wc:"n_ton",Tc:"n_tak",Vc:"n_tipe",Uc:"n_tbti",Xc:"n_taau",Yc:"n_tcu",Zc:"n_tcur",cd:"n_tms",bd:"n_the",ed:"n_ur",fd:"n_uptc",Wb:"n_ugat",kd:"n_uo",jd:"n_ui",gd:"n_ue",hd:"n_ugs",qd:"n_wfp",rd:"n_wcv"};function z(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}y(z,Error);z.prototype.name="CustomError";var ta;function ua(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");z.call(this,c+a[d])}y(ua,z);ua.prototype.name="AssertionError";function va(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new ua(""+e,f||[]);}function A(a,b,c){a||va("",null,b,Array.prototype.slice.call(arguments,2));return a}function B(a,b){throw new ua("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));}
function C(a,b,c){"number"!==typeof a&&va("Expected number but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2));return a}function wa(a,b,c){"string"!==typeof a&&va("Expected string but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2))}function xa(a,b,c){Array.isArray(a)||va("Expected array but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2))};function ya(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function za(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}function Aa(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};function Ba(){var a={DEFAULT:0,DARK:1};this.S={};this.la={};if(a)for(var b in a)this.put(b,a[b])}Ba.prototype.put=function(a,b){A(void 0===this.S[a]);A(void 0===this.la[b]);this.S[a]=b;this.la[b]=a};Ba.prototype.get=function(a){return this.S[a]};Ba.prototype.P=function(){return Aa(this.S)};var Ca=/&/g,Da=/</g,Ea=/>/g,Fa=/"/g,Ga=/'/g,Ha=/\x00/g,Ia=/[\x00&<>"']/;var Ja,Ka;a:{for(var La=["CLOSURE_FLAGS"],Ma=u,Na=0;Na<La.length;Na++)if(Ma=Ma[La[Na]],null==Ma){Ka=null;break a}Ka=Ma}var Oa=Ka&&Ka[610401301];Ja=null!=Oa?Oa:!1;function Pa(){var a=u.navigator;return a&&(a=a.userAgent)?a:""}var D,Qa=u.navigator;D=Qa?Qa.userAgentData||null:null;function Ra(a){return Ja?D?D.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function E(a){return-1!=Pa().indexOf(a)};function G(){return Ja?!!D&&0<D.brands.length:!1}function Sa(){return G()?Ra("Chromium"):(E("Chrome")||E("CriOS"))&&!(G()?0:E("Edge"))||E("Silk")};var Ta=Array.prototype.indexOf?function(a,b){A(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ua=Array.prototype.forEach?function(a,b){A(null!=a.length);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function Va(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Wa(a){Wa[" "](a);return a}Wa[" "]=function(){};var Xa=G()?!1:E("Trident")||E("MSIE"),Ya=E("Gecko")&&!(-1!=Pa().toLowerCase().indexOf("webkit")&&!E("Edge"))&&!(E("Trident")||E("MSIE"))&&!E("Edge"),Za=-1!=Pa().toLowerCase().indexOf("webkit")&&!E("Edge");!E("Android")||Sa();Sa();var $a=E("Safari")&&!(Sa()||(G()?0:E("Coast"))||(G()?0:E("Opera"))||(G()?0:E("Edge"))||(G()?Ra("Microsoft Edge"):E("Edg/"))||(G()?Ra("Opera"):E("OPR"))||E("Firefox")||E("FxiOS")||E("Silk")||E("Android"))&&!(E("iPhone")&&!E("iPod")&&!E("iPad")||E("iPad")||E("iPod"));var H=null,ab=Ya||Za||!$a&&!Xa&&"function"==typeof u.atob;function bb(a,b){function c(h){for(;d<a.length;){var l=a.charAt(d++),n=H[l];if(null!=n)return n;if(!/^[\s\xa0]*$/.test(l))throw Error("Unknown base64 encoding at char: "+l);}return h}cb();for(var d=0;;){var e=c(-1),f=c(0),k=c(64),g=c(64);if(64===g&&-1===e)break;b(e<<2|f>>4);64!=k&&(b(f<<4&240|k>>2),64!=g&&b(k<<6&192|g))}}
function cb(){if(!H){H={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++)for(var d=a.concat(b[c].split("")),e=0;e<d.length;e++){var f=d[e],k=H[f];void 0===k?H[f]=e:A(k===e)}}};A(!0);var db="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol("INTERNAL_ARRAY_STATE"):void 0;A(8===Math.log2(256));var eb=Math,fb=eb.log2,gb=Math.max,hb=gb.apply,ib=Object.values({cc:1,bc:2,ac:4,yc:8,qc:16,gb:32,ad:64,Qb:128,Pb:256,Vb:512}),jb;if(ib instanceof Array)jb=ib;else{for(var kb=r(ib),lb,mb=[];!(lb=kb.next()).done;)mb.push(lb.value);jb=mb}A(9===fb.call(eb,hb.call(gb,Math,jb)));var nb=Object.getOwnPropertyDescriptor(Array.prototype,"Ca");
Object.defineProperties(Array.prototype,{Ca:{get:function(){function a(e,f){e&b&&c.push(f)}var b=ob(this),c=[];a(1,"IS_REPEATED_FIELD");a(2,"IS_IMMUTABLE_ARRAY");a(4,"IS_API_FORMATTED");a(8,"ONLY_MUTABLE_VALUES");a(16,"MUTABLE_REFERENCES_ARE_OWNED");a(32,"CONSTRUCTED");a(64,"TRANSFERRED");a(128,"HAS_SPARSE_OBJECT");a(256,"HAS_MESSAGE_ID");a(512,"IMMUTABLE_CACHED_VALUE_IS_CLEAN");var d=pb(b);536870912!==d&&c.push("pivot: "+d);d=c.join(",");return nb?nb.get.call(this)+"|"+d:d},configurable:!0,enumerable:!1}});
var ob=db?function(a){xa(a,"state is only maintained on arrays.");return a[db]|0}:function(a){xa(a,"state is only maintained on arrays.");return a.td|0};function pb(a){a=a>>10&1023;return 0===a?536870912:a};function qb(){throw Error("please construct maps as mutable then call toImmutable");}
if("undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance){var rb=function(){throw Error("Cannot perform instanceof checks on ImmutableMap: please use isImmutableMap or isMutableMap to assert on the mutability of a map. See go/jspb-api-gotchas#immutable-classes for more information");},sb={};Object.defineProperties(qb,(sb[Symbol.hasInstance]={value:rb,configurable:!1,writable:!1,enumerable:!1},sb));A(qb[Symbol.hasInstance]===rb,"defineProperties did not work: was it monkey-patched?")};if("undefined"!==typeof Proxy){var I=tb;new Proxy({},{getPrototypeOf:I,setPrototypeOf:I,isExtensible:I,preventExtensions:I,getOwnPropertyDescriptor:I,defineProperty:I,has:I,get:I,set:I,deleteProperty:I,apply:I,construct:I})}function tb(){throw Error("this array or object is owned by JSPB and should not be reused, did you mean to copy it with copyJspbArray? See go/jspb-api-gotchas#construct_from_array");throw Error();};function ub(){};(function(){var a=u.jspbGetTypeName;u.jspbGetTypeName=a?function(b){return a(b)||void 0}:ub})();var vb={Ha:"activedescendant",Qa:"atomic",Ra:"autocomplete",Ua:"busy",Ya:"checked",fb:"colindex",hb:"controls",ib:"current",lb:"describedby",DISABLED:"disabled",pb:"dropeffect",Hb:"expanded",Kb:"flowto",Mb:"grabbed",Ob:"haspopup",Sb:"hidden",Zb:"invalid",fc:"label",hc:"labelledby",ic:"level",kc:"live",nc:"multiline",oc:"multiselectable",zc:"orientation",Ac:"owns",Dc:"posinset",Ec:"pressed",Fc:"readonly",Ic:"relevant",Kc:"required",Lc:"rowindex",Mc:"selected",Oc:"setsize",Qc:"sort",ld:"valuemax",md:"valuemin",
nd:"valuenow",od:"valuetext"};var wb;try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var xb;function J(a,b){this.ea=a===yb&&b||"";this.ua=zb}J.prototype.G=!0;J.prototype.C=function(){return this.ea};J.prototype.toString=function(){return"Const{"+this.ea+"}"};function Ab(a){if(a instanceof J&&a.constructor===J&&a.ua===zb)return a.ea;B("expected object of type Const, got '"+a+"'");return"type_error:Const"}var zb={},yb={};function K(a,b){if(b!==L)throw Error("SafeUrl is not meant to be built directly");this.ca=a}K.prototype.toString=function(){return this.ca.toString()};K.prototype.G=!0;K.prototype.C=function(){return this.ca.toString()};var L={};new K("about:invalid#zClosurez",L);new K("about:blank",L);var Bb={};function Cb(){if(Bb!==Bb)throw Error("SafeStyle is not meant to be built directly");this.ra="";this.G=!0}Cb.prototype.C=function(){return this.ra};Cb.prototype.toString=function(){return this.ra.toString()};new Cb;var Db={};function Eb(){if(Db!==Db)throw Error("SafeStyleSheet is not meant to be built directly");this.qa="";this.G=!0}Eb.prototype.toString=function(){return this.qa.toString()};Eb.prototype.C=function(){return this.qa};new Eb;var Fb={};function M(a,b){if(b!==Fb)throw Error("SafeHtml is not meant to be built directly");this.ba=a;this.G=!0}M.prototype.C=function(){return this.ba.toString()};M.prototype.toString=function(){return this.ba.toString()};function Gb(a){if(a instanceof M&&a.constructor===M)return a.ba;B("expected object of type SafeHtml, got '"+a+"' of type "+v(a));return"type_error:SafeHtml"}
function Hb(a){a instanceof M||(a="object"==typeof a&&a.G?a.C():String(a),Ia.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(Ca,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(Da,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(Ea,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(Fa,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(Ga,"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(Ha,"&#0;"))),a=Ib(a));return a}
function Ib(a){if(void 0===xb){var b=null;var c=u.trustedTypes;if(c&&c.createPolicy)try{b=c.createPolicy("goog#html",{createHTML:ra,createScript:ra,createScriptURL:ra})}catch(d){u.console&&u.console.error(d.message)}xb=b}a=(b=xb)?b.createHTML(a):a;return new M(a,Fb)}var Jb=new M(u.trustedTypes&&u.trustedTypes.emptyHTML||"",Fb);var Kb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if("undefined"===typeof document)return!1;var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);if(!a.firstChild)return!1;b=a.firstChild.firstChild;a.innerHTML=Gb(Jb);return!b.parentElement});var Lb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Mb(a,b,c){function d(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):g)}for(var e=1;e<c.length;e++){var f=c[e];if(!w(f)||x(f)&&0<f.nodeType)d(f);else{a:{if(f&&"number"==typeof f.length){if(x(f)){var k="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){k="function"==typeof f.item;break a}}k=!1}Ua(k?Va(f):f,d)}}}function Nb(a){A(a,"Node cannot be null or undefined.");return 9==a.nodeType?a:a.ownerDocument||a.document}
function Ob(){this.J=u.document||document}m=Ob.prototype;m.getElementsByTagName=function(a,b){return(b||this.J).getElementsByTagName(String(a))};m.setProperties=function(a,b){ya(b,function(c,d){c&&"object"==typeof c&&c.G&&(c=c.C());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Lb.hasOwnProperty(d)?a.setAttribute(Lb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})};
m.createElement=function(a){var b=this.J;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};m.createTextNode=function(a){return this.J.createTextNode(String(a))};m.getWindow=function(){var a=this.J;return a.parentWindow||a.defaultView};m.appendChild=function(a,b){A(null!=a&&null!=b,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};m.append=function(a,b){Mb(Nb(a),a,arguments)};
m.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};m.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};
m.getChildren=function(a){return void 0!=a.children?a.children:Array.prototype.filter.call(a.childNodes,function(b){return 1==b.nodeType})};m.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function Pb(a,b,c){Array.isArray(c)&&(c=c.join(" "));var d=Qb(b);""===c||void 0==c?(wb||(c={},wb=(c.atomic=!1,c.autocomplete="none",c.dropeffect="none",c.haspopup=!1,c.live="off",c.multiline=!1,c.multiselectable=!1,c.orientation="vertical",c.readonly=!1,c.relevant="additions text",c.required=!1,c.sort="none",c.busy=!1,c.disabled=!1,c.hidden=!1,c.invalid="false",c)),c=wb,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function Qb(a){A(a,"ARIA attribute cannot be empty.");a:{for(b in vb)if(vb[b]==a){var b=!0;break a}b=!1}A(b,"No such ARIA attribute "+a);return"aria-"+a};function Rb(){this.W=this.W}Rb.prototype.W=!1;Rb.prototype.isDisposed=function(){return this.W};function Sb(a){Rb.call(this);this.ha=a||ta||(ta=new Ob);this.oa={};this.na={}}y(Sb,Rb);var Tb=[];function Ub(a){A(!Object.isSealed(a),"Cannot use getInstance() with a sealed constructor.");var b="Z";if(a.Z&&a.hasOwnProperty(b))return a.Z;Tb.push(a);var c=new a;a.Z=c;A(a.hasOwnProperty(b),"Could not instantiate singleton.");return c};function Vb(){this.va=new Sb}
Vb.prototype.speak=function(a,b){var c=this.va;b=b||"polite";var d;if(d=c.oa[b])d.removeAttribute(Qb("hidden"));else{var e=d=c.ha.createElement("DIV");var f=d;f=Object.prototype.hasOwnProperty.call(f,ma)&&f[ma]||(f[ma]=++na);e.id="goog-lr-"+f;d.style.position="absolute";d.style.top="-1000px";d.style.height="1px";d.style.overflow="hidden";Pb(d,"live",b);Pb(d,"atomic","true");c.ha.J.body.appendChild(d);c.oa[b]=d}e=(e=c.na[b])&&e===a?a+"\u00a0":a;a&&(c.na[b]=e);A(null!=d,"goog.dom.setTextContent expects a non-null value for node");
if("textContent"in d)d.textContent=e;else if(3==d.nodeType)d.data=String(e);else if(d.firstChild&&3==d.firstChild.nodeType){for(;d.lastChild!=d.firstChild;)d.removeChild(A(d.lastChild));d.firstChild.data=String(e)}else{for(;a=d.firstChild;)d.removeChild(a);a=Nb(d);d.appendChild(a.createTextNode(String(e)))}};function Wb(a){if(a.D&&"function"==typeof a.D)return a.D();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(w(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function Xb(a){if(a.P&&"function"==typeof a.P)return a.P();if(!a.D||"function"!=typeof a.D){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&a instanceof Set)){if(w(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}return Aa(a)}}}
function Yb(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(w(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,c);else for(var d=Xb(a),e=Wb(a),f=e.length,k=0;k<f;k++)b.call(c,e[k],d&&d[k],a)};var Zb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function $b(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function N(a){this.u=this.F=this.A="";this.H=null;this.B=this.s="";this.m=this.Ba=!1;if(a instanceof N){this.m=a.m;ac(this,a.A);var b=a.F;O(this);this.F=b;b=a.u;O(this);this.u=b;bc(this,a.H);b=a.s;O(this);this.s=b;cc(this,a.o.clone());a=a.B;O(this);this.B=a}else a&&(b=String(a).match(Zb))?(this.m=!1,ac(this,b[1]||"",!0),a=b[2]||"",O(this),this.F=P(a),a=b[3]||"",O(this),this.u=P(a,!0),bc(this,b[4]),a=b[5]||"",O(this),this.s=P(a,!0),cc(this,b[6]||"",!0),a=b[7]||"",O(this),this.B=P(a)):(this.m=!1,this.o=
new Q(null,this.m))}m=N.prototype;m.toString=function(){var a=[],b=this.A;b&&a.push(R(b,dc,!0),":");var c=this.u;if(c||"file"==b)a.push("//"),(b=this.F)&&a.push(R(b,dc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.H,null!=c&&a.push(":",String(c));if(c=this.s)this.u&&"/"!=c.charAt(0)&&a.push("/"),a.push(R(c,"/"==c.charAt(0)?ec:fc,!0));(c=this.o.toString())&&a.push("?",c);(c=this.B)&&a.push("#",R(c,gc));return a.join("")};
m.resolve=function(a){var b=this.clone(),c=!!a.A;c?ac(b,a.A):c=!!a.F;if(c){var d=a.F;O(b);b.F=d}else c=!!a.u;c?(d=a.u,O(b),b.u=d):c=null!=a.H;d=a.s;if(c)bc(b,a.H);else if(c=!!a.s){if("/"!=d.charAt(0))if(this.u&&!this.s)d="/"+d;else{var e=b.s.lastIndexOf("/");-1!=e&&(d=b.s.slice(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],k=0;k<e.length;){var g=e[k++];"."==g?d&&k==e.length&&f.push(""):".."==g?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),d&&k==e.length&&f.push("")):(f.push(g),d=!0)}d=f.join("/")}else d=e}c?(O(b),b.s=d):c=""!==a.o.toString();c?cc(b,a.o.clone()):c=!!a.B;c&&(a=a.B,O(b),b.B=a);return b};m.clone=function(){return new N(this)};function ac(a,b,c){O(a);a.A=c?P(b,!0):b;a.A&&(a.A=a.A.replace(/:$/,""))}function bc(a,b){O(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.H=b}else a.H=null}
function cc(a,b,c){O(a);b instanceof Q?(a.o=b,a.o.da(a.m)):(c||(b=R(b,hc)),a.o=new Q(b,a.m))}m.getQuery=function(){return this.o.toString()};m.removeParameter=function(a){O(this);this.o.remove(a);return this};function O(a){if(a.Ba)throw Error("Tried to modify a read-only Uri");}m.da=function(a){this.m=a;this.o&&this.o.da(a)};function P(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}
function R(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,ic),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function ic(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var dc=/[#\/\?@]/g,fc=/[#\?:]/g,ec=/[#\?]/g,hc=/[#\?@]/g,gc=/#/g;function Q(a,b){this.i=this.g=null;this.l=a||null;this.m=!!b}function S(a){a.g||(a.g=new Map,a.i=0,a.l&&$b(a.l,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}m=Q.prototype;
m.add=function(a,b){S(this);this.l=null;a=T(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.i=C(this.i)+1;return this};m.remove=function(a){S(this);a=T(this,a);return this.g.has(a)?(this.l=null,this.i=C(this.i)-this.g.get(a).length,this.g.delete(a)):!1};m.clear=function(){this.g=this.l=null;this.i=0};function jc(a,b){S(a);b=T(a,b);return a.g.has(b)}m.forEach=function(a,b){S(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};
m.P=function(){S(this);for(var a=Array.from(this.g.values()),b=Array.from(this.g.keys()),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};m.D=function(a){S(this);var b=[];if("string"===typeof a)jc(this,a)&&(b=b.concat(this.g.get(T(this,a))));else{a=Array.from(this.g.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};
m.set=function(a,b){S(this);this.l=null;a=T(this,a);jc(this,a)&&(this.i=C(this.i)-this.g.get(a).length);this.g.set(a,[b]);this.i=C(this.i)+1;return this};m.get=function(a,b){if(!a)return b;a=this.D(a);return 0<a.length?String(a[0]):b};
m.toString=function(){if(this.l)return this.l;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.D(d);for(var f=0;f<d.length;f++){var k=e;""!==d[f]&&(k+="="+encodeURIComponent(String(d[f])));a.push(k)}}return this.l=a.join("&")};m.clone=function(){var a=new Q;a.l=this.l;this.g&&(a.g=new Map(this.g),a.i=this.i);return a};function T(a,b){b=String(b);a.m&&(b=b.toLowerCase());return b}
m.da=function(a){a&&!this.m&&(S(this),this.l=null,this.g.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<b.length&&(this.l=null,this.g.set(T(this,d),Va(b)),this.i=C(this.i)+b.length))},this));this.m=a};m.extend=function(a){for(var b=0;b<arguments.length;b++)Yb(arguments[b],function(c,d){this.add(d,c)},this)};function kc(){this.ja={};lc(this,u._notes_flag_initialData||{});mc(this)}function lc(a,b){ya(sa,function(c){void 0!==b[c]&&(a.ja[c]=b[c])})}function mc(a){var b={};(new N(self.location.href)).o.forEach(function(c,d){b[d]=c});lc(a,b)};Object.values({UNKNOWN:"unknown",kb:"default",Nb:"groceries",Lb:"food",pc:"music",Gc:"recipes",uc:"notes",Cc:"places",dd:"travel",pd:"video",Xa:"celebration"}).filter(function(a){return"unknown"!==a});var nc=Object.freeze||function(a){return a};function oc(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=!1}oc.prototype.stopPropagation=function(){};oc.prototype.preventDefault=function(){this.defaultPrevented=!0};var pc=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};u.addEventListener("test",c,b);u.removeEventListener("test",c,b)}catch(d){}return a}();function U(a,b){oc.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.K=null;a&&this.init(a,b)}y(U,oc);var qc=nc({2:"touch",3:"pen",4:"mouse"});
U.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(Ya){a:{try{Wa(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=
d.screenY||0):(this.offsetX=Za||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=Za||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=
a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:qc[a.pointerType]||"";this.state=a.state;this.K=a;a.defaultPrevented&&U.T.preventDefault.call(this)};U.prototype.stopPropagation=function(){U.T.stopPropagation.call(this);this.K.stopPropagation?this.K.stopPropagation():this.K.cancelBubble=!0};U.prototype.preventDefault=function(){U.T.preventDefault.call(this);var a=this.K;a.preventDefault?a.preventDefault():a.returnValue=!1};var rc="closure_listenable_"+(1E6*Math.random()|0);var sc=0;function tc(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.X=e;this.key=++sc;this.removed=this.V=!1}function uc(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.X=null};function vc(a){this.src=a;this.j={};this.M=0}m=vc.prototype;m.add=function(a,b,c,d,e){var f=a.toString();a=this.j[f];a||(a=this.j[f]=[],this.M++);var k=wc(a,b,d,e);-1<k?(b=a[k],c||(b.V=!1)):(b=new tc(b,this.src,f,!!d,e),b.V=c,a.push(b));return b};m.remove=function(a,b,c,d){a=a.toString();if(!(a in this.j))return!1;var e=this.j[a];b=wc(e,b,c,d);return-1<b?(uc(e[b]),A(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.j[a],this.M--),!0):!1};
function xc(a,b){var c=b.type;if(c in a.j){var d=a.j[c],e=Ta(d,b),f;if(f=0<=e)A(null!=d.length),Array.prototype.splice.call(d,e,1);f&&(uc(b),0==a.j[c].length&&(delete a.j[c],a.M--))}}m.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.j)if(!a||c==a){for(var d=this.j[c],e=0;e<d.length;e++)++b,uc(d[e]);delete this.j[c];this.M--}return b};m.ya=function(a,b,c,d){a=this.j[a.toString()];var e=-1;a&&(e=wc(a,b,c,d));return-1<e?a[e]:null};
m.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return za(this.j,function(f){for(var k=0;k<f.length;++k)if(!(c&&f[k].type!=d||e&&f[k].capture!=b))return!0;return!1})};function wc(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.X==d)return e}return-1};var yc="closure_lm_"+(1E6*Math.random()|0),zc={},Ac=0;function Bc(a,b,c,d,e){if(d&&d.once)Cc(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)Bc(a,b[f],c,d,e);else c=Dc(c),a&&a[rc]?a.listen(b,c,x(d)?!!d.capture:!!d,e):Ec(a,b,c,!1,d,e)}
function Ec(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=x(e)?!!e.capture:!!e,g=Fc(a);g||(a[yc]=g=new vc(a));c=g.add(b,c,d,k,f);if(!c.proxy){d=Gc();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)pc||(e=k),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Hc(b.toString()),d);else if(a.addListener&&a.removeListener)A("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");
Ac++}}function Gc(){function a(c){return b.call(a.src,a.listener,c)}var b=Ic;return a}function Cc(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Cc(a,b[f],c,d,e);else c=Dc(c),a&&a[rc]?a.ia.add(String(b),c,!0,x(d)?!!d.capture:!!d,e):Ec(a,b,c,!0,d,e)}function Jc(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Jc(a,b[f],c,d,e);else d=x(d)?!!d.capture:!!d,c=Dc(c),a&&a[rc]?a.ia.remove(String(b),c,d,e):a&&(a=Fc(a))&&(b=a.ya(b,c,d,e))&&Kc(b)}
function Kc(a){if("number"!==typeof a&&a&&!a.removed){var b=a.src;if(b&&b[rc])xc(b.ia,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Hc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ac--;(c=Fc(b))?(xc(c,a),0==c.M&&(c.src=null,b[yc]=null)):uc(a)}}}function Hc(a){return a in zc?zc[a]:zc[a]="on"+a}function Ic(a,b){if(a.removed)a=!0;else{b=new U(b,this);var c=a.listener,d=a.X||a.src;a.V&&Kc(a);a=c.call(d,b)}return a}
function Fc(a){a=a[yc];return a instanceof vc?a:null}var Lc="__closure_events_fn_"+(1E9*Math.random()>>>0);function Dc(a){A(a,"Listener can not be null.");if("function"===typeof a)return a;A(a.handleEvent,"An object listener must have handleEvent method.");a[Lc]||(a[Lc]=function(b){return a.handleEvent(b)});return a[Lc]};function V(){this.U=[];new DataView(new ArrayBuffer(8))}function W(){}V.prototype=ea(W.prototype);V.prototype.constructor=V;if(ka)ka(V,W);else for(var X in W)if("prototype"!=X)if(Object.defineProperties){var Mc=Object.getOwnPropertyDescriptor(W,X);Mc&&Object.defineProperty(V,X,Mc)}else V[X]=W[X];V.T=W.prototype;new V;new Ba;(function(a,b){if(ab&&!b)return u.atob(a);var c="";bb(a,function(d){c+=String.fromCharCode(d)});return c})("bGFiZWxz");Object.freeze("annotationsGroup isArchived isDirty isPinned lastSyncedText parentServerId reminder baseVersion baseNoteRevision serverId shareState roleInfo showAvailableInShoppingNotification timestamps".split(" "));new K(Ab(new J(yb,"http://goo.gl/forms/r40gTO4BTb")),L);new K(Ab(new J(yb,"https://keep.google.com")),L);function Nc(a,b){this.name=a;this.value=b}Nc.prototype.toString=function(){return this.name};var Oc=new Nc("OFF",Infinity),Pc=new Nc("WARNING",900),Qc=new Nc("CONFIG",700);function Rc(){this.O=0;this.clear()}var Sc;Rc.prototype.clear=function(){this.U=Array(this.O);this.ga=-1;this.ma=!1};function Tc(a,b,c){this.reset(a||Oc,b,c,void 0,void 0)}Tc.prototype.reset=function(a,b){this.Ea=b};Tc.prototype.getMessage=function(){return this.Ea};
function Uc(a,b){this.level=null;this.Aa=[];this.parent=(void 0===b?null:b)||null;this.children=[];this.Da={getName:function(){return a}}}function Vc(a){if(a.level)return a.level;if(a.parent)return Vc(a.parent);B("Root logger has no level set.");return Oc}Uc.prototype.publish=function(a){for(var b=this;b;)b.Aa.forEach(function(c){c(a)}),b=b.parent};function Wc(){this.entries={};var a=new Uc("");a.level=Qc;this.entries[""]=a}var Xc;
function Yc(a,b){var c=a.entries[b];if(c)return c;c=Yc(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var d=new Uc(b,c);a.entries[b]=d;c.children.push(d);return d}function Zc(){Xc||(Xc=new Wc);return Xc};/*

 SPDX-License-Identifier: Apache-2.0
*/
var $c;try{new URL("s://g"),$c=!0}catch(a){$c=!1}var ad=$c,bd=[];function cd(){}
dd(function(a){var b;if(b=Yc(Zc(),"safevalues").Da){var c="A URL with content '"+a+"' was sanitized away.",d=Pc;if(a=b)if(a=b&&d){a=d.value;var e=b?Vc(Yc(Zc(),b.getName())):Oc;a=a>=e.value}if(a){d=d||Oc;a=Yc(Zc(),b.getName());"function"===typeof c&&(c=c());Sc||(Sc=new Rc);e=Sc;b=b.getName();if(0<e.O){var f=(e.ga+1)%e.O;e.ga=f;e.ma?(e=e.U[f],e.reset(d,c,b),b=e):(e.ma=f==e.O-1,b=e.U[f]=new Tc(d,c,b))}else b=new Tc(d,c,b);a.publish(b)}}});
function dd(a){-1===bd.indexOf(a)&&bd.push(a);cd=function(b){bd.forEach(function(c){c(b)})}};var ed={ud:!0};function Y(){throw Error("Do not instantiate directly");}Y.prototype.wa=null;Y.prototype.getContent=function(){return this.content};Y.prototype.toString=function(){return this.content};
Y.prototype.sa=function(){if(this.xa!==ed)throw Error("Sanitized content was not of kind HTML.");var a=this.toString(),b=new J(yb,"Soy SanitizedContent of kind HTML produces SafeHtml-contract-compliant value.");wa(Ab(b),"must provide justification");A(!/^[\s\xa0]*$/.test(Ab(b)),"must provide non-empty justification");return Ib(a)};function fd(){Y.call(this)}y(fd,Y);fd.prototype.xa=ed;var gd=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.wa=d);return c}}(fd),hd={};/*
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var id=/^<(body|caption|col|colgroup|head|html|tr|td|th|tbody|thead|tfoot)>/i,jd={};function kd(){var a=Ub(kc).ja.n_ecmv3m;this.R=!!a&&"false"!==a;this.h=null;this.aa=!1;this.fa="";this.R&&(this.N={});this.R||(this.Y(),Bc(document,"mousedown",this.ka,void 0,this),a={},a.imageUrl=ld(),Z(this,"pageScrape",a));this.pa=qa(this.za,this);chrome.runtime.onMessage.addListener(this.pa)}function md(a){a.h=null;a.R||Jc(document,"mousedown",a.ka,void 0,a);chrome.runtime.onMessage.removeListener(a.pa);a.aa=!0}
function Z(a,b,c){if(!a.aa)try{chrome.runtime.sendMessage(chrome.runtime.id,{type:b,value:c},void 0)}catch(d){md(a)}}
function ld(){for(var a="",b=document.getElementsByTagName("META"),c=0,d;d=b[c];c++)if("og:image"==d.getAttribute("property")){a=d.getAttribute("content");break}if(!a){b=0;c=document.getElementsByTagName("IMG");d=0;for(var e;e=c[d];d++){var f=e.naturalWidth||e.width,k=e.naturalHeight||e.height;if(128<=k&&128<=f&&k*f>b){b=k*f;var g=e.src}}g&&(a=g)}a&&(a=a instanceof N?a.clone():new N(a),a.A||ac(a,"http"),a=a.toString());return a}
kd.prototype.za=function(a,b,c){if(x(a)&&!this.aa)switch(a.type){case "appHeightChange":this.h&&(this.h.style.height=a.value);break;case "dispose":md(this);break;case "finishHide":this.h&&nd(this,!1);break;case "getInitInfo":c(this.N);break;case "getSelectedText":c(window.getSelection().toString());break;case "removeIframe":this.h.parentNode.removeChild(this.h),md(this);case "selectedTextRequest":c(window.getSelection().toString());break;case "setInitInfo":this.N=a.value;this.N.selectedText=window.getSelection().toString();
this.N.embedInfo.imageUrl=ld();this.Y();break;case "speakMessage":Ub(Vb).speak(a.value);break;case "show":this.h&&nd(this,!0);break;case "toggleVisibility":a="none"==this.h.style.display,this.h&&("none"==this.h.style.display?(nd(this,!0),this.h.contentWindow.focus(),Z(this,"show")):(Z(this,"startHide"),Z(this,"impression",9204))),c(a)}};
kd.prototype.Y=function(){if("interactive"!=document.readyState&&"complete"!=document.readyState)Bc(document,"DOMContentLoaded",this.Y,void 0,this);else{if(this.R){var a=document.getElementById("keep-popup-frame");a&&a.parentNode&&a.parentNode.removeChild(a)}var b=hd["notes.browseraction.soy.injects.injectedIframe"]?hd["notes.browseraction.soy.injects.injectedIframe"](jd,void 0):gd('<iframe frameborder="0" style=" height: 438px; margin: 0px; padding: 0px; position: fixed; right: 5px; top: 5px; width: 370px; z-index: 2147483647;"></iframe>');
a=ta||(ta=new Ob);if(b&&b.Fa)a=b.Fa();else{a=a.createElement("DIV");b:if(x(b)){if(b.sa){var c=b.sa();if(c instanceof M){b=c;break b}}B("Soy template output is unsafe for use as HTML: "+b);b=Hb("zSoyz")}else b=Hb(String(b));c=b.C();var d=c.match(id);A(!d,"This template starts with a %s, which cannot be a child of a <div>, as required by soy internals. Consider using goog.soy.renderElement instead.\nTemplate output: %s",d&&d[0],c);c=a;if(Kb())for(;c.lastChild;)c.removeChild(c.lastChild);c.innerHTML=
Gb(b)}1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));if(!x(a)||!x(a)||!x(a)||1!==a.nodeType||a.namespaceURI&&"http://www.w3.org/1999/xhtml"!==a.namespaceURI||a.tagName.toUpperCase()!=="IFRAME".toString()){b="IFRAME".toString()+"; got: ";if(x(a))try{var e=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(k){e="<object could not be stringified>"}else e=void 0===a?"undefined":null===a?"null":typeof a;B("Argument is not an HTML Element with tag name "+
(b+e))}this.h=a;this.fa=this.h.style.cssText;this.h.id="keep-popup-frame";e=this.h;a=chrome.runtime.getURL("index.html");e.removeAttribute("srcdoc");b="allow-same-origin allow-scripts allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation".split(" ");e.setAttribute("sandbox","");for(c=0;c<b.length;c++)e.sandbox.supports&&!e.sandbox.supports(b[c])||e.sandbox.add(b[c]);if(a instanceof K)if(a instanceof K&&a.constructor===K)var f=a.ca;else B("expected object of type SafeUrl, got '"+
a+"' of type "+v(a)),f="type_error:SafeUrl";else{b:if(ad){try{f=new URL(a)}catch(k){f="https:";break b}f=f.protocol}else c:{f=document.createElement("a");try{f.href=a}catch(k){f=void 0;break c}f=f.protocol;f=":"===f||""===f?"https:":f}"javascript:"===f?(cd(a),f=void 0):f=a}void 0!==f&&(e.src=f);this.h.allow="clipboard-write";document.body.appendChild(this.h);nd(this,!0);this.h.contentWindow.focus()}};function nd(a,b){a.h.style.cssText=a.fa+" display: "+(b?"block !important;":"none")}
kd.prototype.ka=function(a){0==a.button&&this.h&&"none"!=this.h.style.display&&(Z(this,"startHide"),Z(this,"impression",9203))};new kd;
